# default values for templates

namespace: some-namespace

appName: app-service-name
appImage: gcr.io/google-samples/microservices-demo/app-service-name
appVersion: v.0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: "ENV_VAR_1"
  value: "env-var-1-value"
- name: "ENV_VAR_2"
  value: "env-var-2-value"
# add as many env vars as needed

servicePortName: port-name # example: grpc, http
servicePort: 8080
serviceType: ClusterIP # or LoadBalancer
