---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.8.1
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog-service:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "email-service:8080"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  selector:
    app: checkout-service
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
  type: ClusterIP
