---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.1
        ports:
        - containerPort: 7070
        env:
        - name: PORT
          value: "7070"
        - name: DISABLE_PROFILER
          value : "1"
        - name: REDIS_ADDR
          value: "redis-cart:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
  type: ClusterIP
