---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.8.1
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: your-service-name
spec:
  selector:
    app: currency-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP
