appName: ad-service
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v.0.8.1
appReplicas: 2
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"

servicePortName: grpc
servicePort: 9555
serviceType: ClusterIP
