namespace: online-boutique

appName: ad-service
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"
cpuRequests: 200m
memoryRequests: 180Mi
cpuLimits: 300m
memoryLimits: 300Mi

servicePortName: grpc
servicePort: 9555
serviceType: ClusterIP
