namespace: online-boutique

appName: currency-service
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"
cpuRequests: 100m
memoryRequests: 64Mi
cpuLimits: 200m
memoryLimits: 128Mi

servicePortName: grpc
servicePort: 7000
serviceType: ClusterIP
