namespace: online-boutique

appName: email-service
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
cpuRequests: 100m
memoryRequests: 64Mi
cpuLimits: 200m
memoryLimits: 128Mi

servicePortName: grpc
servicePort: 8080
serviceType: ClusterIP
