namespace: online-boutique

appName: frontend-service
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.8.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "product-catalog-service:3550"
- name: CURRENCY_SERVICE_ADDR
  value: "currency-service:7000"
- name: CART_SERVICE_ADDR
  value: "cart-service:7070"
- name: RECOMMENDATION_SERVICE_ADDR
  value: "recommendation-service:8080"
- name: SHIPPING_SERVICE_ADDR
  value: "shipping-service:50051"
- name: CHECKOUT_SERVICE_ADDR
  value: "checkout-service:5050"
- name: AD_SERVICE_ADDR
  value: "ad-service:9555"
# # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
# # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
# - name: ENV_PLATFORM
#   value: "aws"
- name: ENABLE_PROFILER
  value: "0"
# - name: CYMBAL_BRANDING
#   value: "true"
# - name: FRONTEND_MESSAGE
#   value: "Replace this with a message you want to display on all pages."

servicePortName: http
servicePort: 80
serviceType: LoadBalancer
