appName: recommendation-service
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v.0.8.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "product-catalog-service:3550"
- name: DISABLE_PROFILER
  value: "1"

servicePortName: grpc
servicePort: 8080
serviceType: ClusterIP
