namespace: online-boutique

appName: recommendation-service
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "product-catalog-service:3550"
- name: DISABLE_PROFILER
  value: "1"
cpuRequests: 100m
memoryRequests: 220Mi
cpuLimits: 200m
memoryLimits: 450Mi

servicePortName: grpc
servicePort: 8080
serviceType: ClusterIP
