namespace: online-boutique

appName: shipping-service
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.8.1
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"
cpuRequests: 100m
memoryRequests: 64Mi
cpuLimits: 200m
memoryLimits: 128Mi

servicePortName: grpc
servicePort: 50051
serviceType: ClusterIP
